stages:
  data_ingestion:
    cmd: python chrome-plugin\src\data\data_ingestion.py
    deps:
      - chrome-plugin\src\data\data_ingestion.py
    params:
      - data_ingestion.test_size
    outs:
      - chrome-plugin/data/raw  # Mark it as a directory
    
  data_preprocessing:
   cmd: python chrome-plugin\src\data\data_preprocessing.py
   deps:
    - data\raw\train.csv
    - data\raw\test.csv
    - chrome-plugin\src\data\data_preprocessing.py
   outs:
   - chrome-plugin\data\interim
     
          
